In [94]:
import pandas as pd

In [95]:
data = pd.read_excel('Gini.xlsx')

In [96]:
data

,year,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 58,Unnamed: 59
0,country,gini_disp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Argentina,0.3596764603,0.357685,0.356529,0.355791,0.356820,0.356294,0.355157,0.355587,0.357068,...,0.400630,0.393698,0.387748,0.384532,0.380736,0.378133,0.376583,0.376549,NaN,NaN
2,Botswana,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.583041,0.582511,0.581286,0.579866,0.580207,0.581848,NaN,NaN,NaN,NaN
3,Brazil,0.4993695074,0.500768,0.502024,0.502061,0.503268,0.504196,0.504322,0.505540,0.505476,...,0.475220,0.470242,0.467415,0.462132,0.461936,0.464661,0.477127,0.479085,0.478732,NaN
4,Chad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.428642,0.430031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.454539,0.456901,...,0.470489,0.466809,0.464673,0.461788,0.459044,0.455785,0.457536,0.457323,NaN,NaN
6,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.426443,0.425994,0.418234,0.410654,0.410079,0.410305,0.410472,0.411212,NaN,NaN
7,Ecuador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.445093,0.437680,0.431728,0.429536,0.425248,0.424350,0.423510,0.423548,0.423195,NaN
8,Hungary,NaN,0.248479,0.246018,0.242838,0.240887,0.238478,0.236945,0.234872,0.233446,...,0.272935,0.274216,0.278617,0.281376,0.280284,0.277641,0.279134,0.281474,0.280083,NaN
9,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.489253,0.494477,0.494913,0.494873,0.497074,0.497601,NaN,NaN,NaN,NaN
10,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.467310,0.467252,0.466775,0.467404,0.468536,0.469112,NaN,NaN,NaN,NaN
11,Lesotho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.503409,0.500661,0.498179,0.497029,0.495766,0.495672,0.494297,0.493040,NaN,NaN
12,Malawi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.462804,...,0.458446,0.457618,0.455361,0.455178,0.455747,0.456000,0.455456,NaN,NaN,NaN
13,Mauritius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.384773,0.384870,0.385625,0.385809,0.383857,0.384401,0.384921,0.384837,NaN,NaN
14,Mexico,NaN,NaN,0.524117,0.523702,0.521937,0.520762,0.519660,0.520263,0.518196,...,0.455381,0.455284,0.451993,0.449993,0.445655,0.439478,0.434674,0.431231,0.429316,NaN
15,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.385495,0.386667,0.385725,0.385501,0.383168,0.381863,0.382358,NaN,NaN,NaN
16,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.415996,0.416337,0.416655,0.417055,0.416593,NaN,NaN,NaN,NaN,NaN
17,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.669962,0.669075,0.667086,0.667520,0.666560,0.666034,0.665970,NaN,NaN,NaN
18,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.436019,0.435366,0.434272,0.432563,0.430721,0.429833,0.430030,0.427661,0.426735,NaN
19,Pakistan,NaN,NaN,NaN,0.344457,0.342794,0.340498,0.338894,0.336550,0.333447,...,0.343306,0.345336,0.344125,0.343865,0.343749,0.343351,2016.000000,2017.000000,NaN,NaN
20,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.479182,0.479956,0.469079,0.470427,0.469839,0.462783,0.465303,0.462993,0.461303,NaN
21,Peru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.475760,0.464997,0.460379,0.456002,0.449557,0.449204,0.451670,0.449091,0.449207,NaN
22,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.310160,0.307854,0.308317,0.312626,0.304094,0.297596,0.290647,0.287117,0.286017,NaN
23,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.325886,0.326269,0.328916,0.331805,0.336619,0.335716,0.332070,0.335544,0.336459,NaN
24,Rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.512363,0.512786,0.511568,0.511280,0.510751,0.509614,0.510012,NaN,NaN,NaN
25,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.428275,0.428840,0.428965,0.426658,NaN,NaN,NaN,NaN,NaN,NaN
26,S.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.635801,0.634215,0.632759,0.631425,0.629303,0.627564,0.625954,0.625341,NaN,NaN
27,Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.399297,0.397251,0.394169,0.393057,0.392049,0.390968,NaN,NaN,NaN,NaN
28,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.405161,0.403109,0.400751,0.398958,0.398531,0.399537,0.401022,0.401072,0.400838,0.399474
29,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.449548,0.448601,0.447136,0.446677,0.446826,0.447604,0.446422,NaN,NaN,NaN
30,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.558546,0.557177,0.557102,0.558957,0.558794,0.559411,NaN,NaN,NaN,NaN

In [97]:
data.drop(data.iloc[:, 1:44], axis = 1, inplace = True) 
data

,year,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 58,Unnamed: 59
0,country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Argentina,0.452966,0.442450,0.432889,0.422866,0.413669,0.407890,0.400630,0.393698,0.387748,0.384532,0.380736,0.378133,0.376583,0.376549,NaN,NaN
2,Botswana,0.585215,0.584953,0.584686,0.584680,0.584762,0.584536,0.583041,0.582511,0.581286,0.579866,0.580207,0.581848,NaN,NaN,NaN,NaN
3,Brazil,0.509188,0.505514,0.502698,0.492670,0.484497,0.478767,0.475220,0.470242,0.467415,0.462132,0.461936,0.464661,0.477127,0.479085,0.478732,NaN
4,Chad,0.424023,0.425148,0.427591,0.426260,0.426749,0.427589,0.428642,0.430031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Chile,0.492931,0.487240,0.480810,0.478965,0.476601,0.474623,0.470489,0.466809,0.464673,0.461788,0.459044,0.455785,0.457536,0.457323,NaN,NaN
6,China,0.417496,0.419426,0.422826,0.424862,0.427811,0.427153,0.426443,0.425994,0.418234,0.410654,0.410079,0.410305,0.410472,0.411212,NaN,NaN
7,Ecuador,0.488626,0.483989,0.478924,0.472173,0.463364,0.453907,0.445093,0.437680,0.431728,0.429536,0.425248,0.424350,0.423510,0.423548,0.423195,NaN
8,Hungary,0.277325,0.275923,0.272970,0.271036,0.270137,0.271007,0.272935,0.274216,0.278617,0.281376,0.280284,0.277641,0.279134,0.281474,0.280083,NaN
9,India,0.475990,0.477169,0.476792,0.478751,0.481493,0.484761,0.489253,0.494477,0.494913,0.494873,0.497074,0.497601,NaN,NaN,NaN,NaN
10,Kenya,0.470502,0.469579,0.470015,0.467160,0.466891,0.467044,0.467310,0.467252,0.466775,0.467404,0.468536,0.469112,NaN,NaN,NaN,NaN
11,Lesotho,0.509925,0.508952,0.508195,0.507159,0.505095,0.505016,0.503409,0.500661,0.498179,0.497029,0.495766,0.495672,0.494297,0.493040,NaN,NaN
12,Malawi,0.463758,0.460884,0.459149,0.458015,0.457522,0.458489,0.458446,0.457618,0.455361,0.455178,0.455747,0.456000,0.455456,NaN,NaN,NaN
13,Mauritius,0.380992,0.381703,0.382170,0.382051,0.383758,0.385388,0.384773,0.384870,0.385625,0.385809,0.383857,0.384401,0.384921,0.384837,NaN,NaN
14,Mexico,0.471586,0.471145,0.464996,0.464797,0.464740,0.459854,0.455381,0.455284,0.451993,0.449993,0.445655,0.439478,0.434674,0.431231,0.429316,NaN
15,Montenegro,NaN,0.381978,0.381777,0.383230,0.382965,0.385377,0.385495,0.386667,0.385725,0.385501,0.383168,0.381863,0.382358,NaN,NaN,NaN
16,Morocco,0.416425,0.415757,0.414862,0.415598,0.415515,0.415779,0.415996,0.416337,0.416655,0.417055,0.416593,NaN,NaN,NaN,NaN,NaN
17,Namibia,0.673099,0.673610,0.673752,0.673941,0.671761,0.669987,0.669962,0.669075,0.667086,0.667520,0.666560,0.666034,0.665970,NaN,NaN,NaN
18,Nigeria,0.437222,0.436439,0.436412,0.436615,0.436519,0.436415,0.436019,0.435366,0.434272,0.432563,0.430721,0.429833,0.430030,0.427661,0.426735,NaN
19,Pakistan,0.343902,0.344955,0.345055,0.345175,0.344646,0.343180,0.343306,0.345336,0.344125,0.343865,0.343749,0.343351,2016.000000,2017.000000,NaN,NaN
20,Paraguay,0.505215,0.494780,0.492442,0.486264,0.479530,0.475879,0.479182,0.479956,0.469079,0.470427,0.469839,0.462783,0.465303,0.462993,0.461303,NaN
21,Peru,0.524296,0.520375,0.514359,0.505296,0.494336,0.484870,0.475760,0.464997,0.460379,0.456002,0.449557,0.449204,0.451670,0.449091,0.449207,NaN
22,Poland,0.316002,0.318754,0.316789,0.313574,0.311397,0.309840,0.310160,0.307854,0.308317,0.312626,0.304094,0.297596,0.290647,0.287117,0.286017,NaN
23,Romania,0.310488,0.319811,0.329609,0.330487,0.328280,0.325687,0.325886,0.326269,0.328916,0.331805,0.336619,0.335716,0.332070,0.335544,0.336459,NaN
24,Rwanda,0.512383,0.515393,0.513608,0.512745,0.512716,0.513109,0.512363,0.512786,0.511568,0.511280,0.510751,0.509614,0.510012,NaN,NaN,NaN
25,Seychelles,0.427561,0.426687,0.426963,0.426211,0.425823,0.427415,0.428275,0.428840,0.428965,0.426658,NaN,NaN,NaN,NaN,NaN,NaN
26,S.A,0.627275,0.629702,0.632091,0.634358,0.636537,0.635301,0.635801,0.634215,0.632759,0.631425,0.629303,0.627564,0.625954,0.625341,NaN,NaN
27,Tunisia,0.408383,0.406607,0.404747,0.403498,0.402596,0.401282,0.399297,0.397251,0.394169,0.393057,0.392049,0.390968,NaN,NaN,NaN,NaN
28,Turkey,0.420109,0.417709,0.413696,0.411338,0.409656,0.406582,0.405161,0.403109,0.400751,0.398958,0.398531,0.399537,0.401022,0.401072,0.400838,0.399474
29,Uganda,0.452936,0.451785,0.451197,0.451089,0.449898,0.449802,0.449548,0.448601,0.447136,0.446677,0.446826,0.447604,0.446422,NaN,NaN,NaN
30,Zambia,0.550650,0.551710,0.552987,0.555838,0.557042,0.557060,0.558546,0.557177,0.557102,0.558957,0.558794,0.559411,NaN,NaN,NaN,NaN

In [98]:
data = data.rename(columns={'year': 'country'}, index={'ONE': 'one'})

In [99]:
data

,country,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 58,Unnamed: 59
0,country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Argentina,0.452966,0.442450,0.432889,0.422866,0.413669,0.407890,0.400630,0.393698,0.387748,0.384532,0.380736,0.378133,0.376583,0.376549,NaN,NaN
2,Botswana,0.585215,0.584953,0.584686,0.584680,0.584762,0.584536,0.583041,0.582511,0.581286,0.579866,0.580207,0.581848,NaN,NaN,NaN,NaN
3,Brazil,0.509188,0.505514,0.502698,0.492670,0.484497,0.478767,0.475220,0.470242,0.467415,0.462132,0.461936,0.464661,0.477127,0.479085,0.478732,NaN
4,Chad,0.424023,0.425148,0.427591,0.426260,0.426749,0.427589,0.428642,0.430031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Chile,0.492931,0.487240,0.480810,0.478965,0.476601,0.474623,0.470489,0.466809,0.464673,0.461788,0.459044,0.455785,0.457536,0.457323,NaN,NaN
6,China,0.417496,0.419426,0.422826,0.424862,0.427811,0.427153,0.426443,0.425994,0.418234,0.410654,0.410079,0.410305,0.410472,0.411212,NaN,NaN
7,Ecuador,0.488626,0.483989,0.478924,0.472173,0.463364,0.453907,0.445093,0.437680,0.431728,0.429536,0.425248,0.424350,0.423510,0.423548,0.423195,NaN
8,Hungary,0.277325,0.275923,0.272970,0.271036,0.270137,0.271007,0.272935,0.274216,0.278617,0.281376,0.280284,0.277641,0.279134,0.281474,0.280083,NaN
9,India,0.475990,0.477169,0.476792,0.478751,0.481493,0.484761,0.489253,0.494477,0.494913,0.494873,0.497074,0.497601,NaN,NaN,NaN,NaN
10,Kenya,0.470502,0.469579,0.470015,0.467160,0.466891,0.467044,0.467310,0.467252,0.466775,0.467404,0.468536,0.469112,NaN,NaN,NaN,NaN
11,Lesotho,0.509925,0.508952,0.508195,0.507159,0.505095,0.505016,0.503409,0.500661,0.498179,0.497029,0.495766,0.495672,0.494297,0.493040,NaN,NaN
12,Malawi,0.463758,0.460884,0.459149,0.458015,0.457522,0.458489,0.458446,0.457618,0.455361,0.455178,0.455747,0.456000,0.455456,NaN,NaN,NaN
13,Mauritius,0.380992,0.381703,0.382170,0.382051,0.383758,0.385388,0.384773,0.384870,0.385625,0.385809,0.383857,0.384401,0.384921,0.384837,NaN,NaN
14,Mexico,0.471586,0.471145,0.464996,0.464797,0.464740,0.459854,0.455381,0.455284,0.451993,0.449993,0.445655,0.439478,0.434674,0.431231,0.429316,NaN
15,Montenegro,NaN,0.381978,0.381777,0.383230,0.382965,0.385377,0.385495,0.386667,0.385725,0.385501,0.383168,0.381863,0.382358,NaN,NaN,NaN
16,Morocco,0.416425,0.415757,0.414862,0.415598,0.415515,0.415779,0.415996,0.416337,0.416655,0.417055,0.416593,NaN,NaN,NaN,NaN,NaN
17,Namibia,0.673099,0.673610,0.673752,0.673941,0.671761,0.669987,0.669962,0.669075,0.667086,0.667520,0.666560,0.666034,0.665970,NaN,NaN,NaN
18,Nigeria,0.437222,0.436439,0.436412,0.436615,0.436519,0.436415,0.436019,0.435366,0.434272,0.432563,0.430721,0.429833,0.430030,0.427661,0.426735,NaN
19,Pakistan,0.343902,0.344955,0.345055,0.345175,0.344646,0.343180,0.343306,0.345336,0.344125,0.343865,0.343749,0.343351,2016.000000,2017.000000,NaN,NaN
20,Paraguay,0.505215,0.494780,0.492442,0.486264,0.479530,0.475879,0.479182,0.479956,0.469079,0.470427,0.469839,0.462783,0.465303,0.462993,0.461303,NaN
21,Peru,0.524296,0.520375,0.514359,0.505296,0.494336,0.484870,0.475760,0.464997,0.460379,0.456002,0.449557,0.449204,0.451670,0.449091,0.449207,NaN
22,Poland,0.316002,0.318754,0.316789,0.313574,0.311397,0.309840,0.310160,0.307854,0.308317,0.312626,0.304094,0.297596,0.290647,0.287117,0.286017,NaN
23,Romania,0.310488,0.319811,0.329609,0.330487,0.328280,0.325687,0.325886,0.326269,0.328916,0.331805,0.336619,0.335716,0.332070,0.335544,0.336459,NaN
24,Rwanda,0.512383,0.515393,0.513608,0.512745,0.512716,0.513109,0.512363,0.512786,0.511568,0.511280,0.510751,0.509614,0.510012,NaN,NaN,NaN
25,Seychelles,0.427561,0.426687,0.426963,0.426211,0.425823,0.427415,0.428275,0.428840,0.428965,0.426658,NaN,NaN,NaN,NaN,NaN,NaN
26,S.A,0.627275,0.629702,0.632091,0.634358,0.636537,0.635301,0.635801,0.634215,0.632759,0.631425,0.629303,0.627564,0.625954,0.625341,NaN,NaN
27,Tunisia,0.408383,0.406607,0.404747,0.403498,0.402596,0.401282,0.399297,0.397251,0.394169,0.393057,0.392049,0.390968,NaN,NaN,NaN,NaN
28,Turkey,0.420109,0.417709,0.413696,0.411338,0.409656,0.406582,0.405161,0.403109,0.400751,0.398958,0.398531,0.399537,0.401022,0.401072,0.400838,0.399474
29,Uganda,0.452936,0.451785,0.451197,0.451089,0.449898,0.449802,0.449548,0.448601,0.447136,0.446677,0.446826,0.447604,0.446422,NaN,NaN,NaN
30,Zambia,0.550650,0.551710,0.552987,0.555838,0.557042,0.557060,0.558546,0.557177,0.557102,0.558957,0.558794,0.559411,NaN,NaN,NaN,NaN

In [100]:
data.drop([0], inplace = True)

In [101]:
data.drop(data.columns[[13,14,15,16]], axis=1, inplace = True)

In [102]:
data

,country,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
1,Argentina,0.452966,0.442450,0.432889,0.422866,0.413669,0.407890,0.400630,0.393698,0.387748,0.384532,0.380736,0.378133
2,Botswana,0.585215,0.584953,0.584686,0.584680,0.584762,0.584536,0.583041,0.582511,0.581286,0.579866,0.580207,0.581848
3,Brazil,0.509188,0.505514,0.502698,0.492670,0.484497,0.478767,0.475220,0.470242,0.467415,0.462132,0.461936,0.464661
4,Chad,0.424023,0.425148,0.427591,0.426260,0.426749,0.427589,0.428642,0.430031,NaN,NaN,NaN,NaN
5,Chile,0.492931,0.487240,0.480810,0.478965,0.476601,0.474623,0.470489,0.466809,0.464673,0.461788,0.459044,0.455785
6,China,0.417496,0.419426,0.422826,0.424862,0.427811,0.427153,0.426443,0.425994,0.418234,0.410654,0.410079,0.410305
7,Ecuador,0.488626,0.483989,0.478924,0.472173,0.463364,0.453907,0.445093,0.437680,0.431728,0.429536,0.425248,0.424350
8,Hungary,0.277325,0.275923,0.272970,0.271036,0.270137,0.271007,0.272935,0.274216,0.278617,0.281376,0.280284,0.277641
9,India,0.475990,0.477169,0.476792,0.478751,0.481493,0.484761,0.489253,0.494477,0.494913,0.494873,0.497074,0.497601
10,Kenya,0.470502,0.469579,0.470015,0.467160,0.466891,0.467044,0.467310,0.467252,0.466775,0.467404,0.468536,0.469112
11,Lesotho,0.509925,0.508952,0.508195,0.507159,0.505095,0.505016,0.503409,0.500661,0.498179,0.497029,0.495766,0.495672
12,Malawi,0.463758,0.460884,0.459149,0.458015,0.457522,0.458489,0.458446,0.457618,0.455361,0.455178,0.455747,0.456000
13,Mauritius,0.380992,0.381703,0.382170,0.382051,0.383758,0.385388,0.384773,0.384870,0.385625,0.385809,0.383857,0.384401
14,Mexico,0.471586,0.471145,0.464996,0.464797,0.464740,0.459854,0.455381,0.455284,0.451993,0.449993,0.445655,0.439478
15,Montenegro,NaN,0.381978,0.381777,0.383230,0.382965,0.385377,0.385495,0.386667,0.385725,0.385501,0.383168,0.381863
16,Morocco,0.416425,0.415757,0.414862,0.415598,0.415515,0.415779,0.415996,0.416337,0.416655,0.417055,0.416593,NaN
17,Namibia,0.673099,0.673610,0.673752,0.673941,0.671761,0.669987,0.669962,0.669075,0.667086,0.667520,0.666560,0.666034
18,Nigeria,0.437222,0.436439,0.436412,0.436615,0.436519,0.436415,0.436019,0.435366,0.434272,0.432563,0.430721,0.429833
19,Pakistan,0.343902,0.344955,0.345055,0.345175,0.344646,0.343180,0.343306,0.345336,0.344125,0.343865,0.343749,0.343351
20,Paraguay,0.505215,0.494780,0.492442,0.486264,0.479530,0.475879,0.479182,0.479956,0.469079,0.470427,0.469839,0.462783
21,Peru,0.524296,0.520375,0.514359,0.505296,0.494336,0.484870,0.475760,0.464997,0.460379,0.456002,0.449557,0.449204
22,Poland,0.316002,0.318754,0.316789,0.313574,0.311397,0.309840,0.310160,0.307854,0.308317,0.312626,0.304094,0.297596
23,Romania,0.310488,0.319811,0.329609,0.330487,0.328280,0.325687,0.325886,0.326269,0.328916,0.331805,0.336619,0.335716
24,Rwanda,0.512383,0.515393,0.513608,0.512745,0.512716,0.513109,0.512363,0.512786,0.511568,0.511280,0.510751,0.509614
25,Seychelles,0.427561,0.426687,0.426963,0.426211,0.425823,0.427415,0.428275,0.428840,0.428965,0.426658,NaN,NaN
26,S.A,0.627275,0.629702,0.632091,0.634358,0.636537,0.635301,0.635801,0.634215,0.632759,0.631425,0.629303,0.627564
27,Tunisia,0.408383,0.406607,0.404747,0.403498,0.402596,0.401282,0.399297,0.397251,0.394169,0.393057,0.392049,0.390968
28,Turkey,0.420109,0.417709,0.413696,0.411338,0.409656,0.406582,0.405161,0.403109,0.400751,0.398958,0.398531,0.399537
29,Uganda,0.452936,0.451785,0.451197,0.451089,0.449898,0.449802,0.449548,0.448601,0.447136,0.446677,0.446826,0.447604
30,Zambia,0.550650,0.551710,0.552987,0.555838,0.557042,0.557060,0.558546,0.557177,0.557102,0.558957,0.558794,0.559411

In [103]:
data.set_index(['country'])

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
country,,,,,,,,,,,,
Argentina,0.452966,0.442450,0.432889,0.422866,0.413669,0.407890,0.400630,0.393698,0.387748,0.384532,0.380736,0.378133
Botswana,0.585215,0.584953,0.584686,0.584680,0.584762,0.584536,0.583041,0.582511,0.581286,0.579866,0.580207,0.581848
Brazil,0.509188,0.505514,0.502698,0.492670,0.484497,0.478767,0.475220,0.470242,0.467415,0.462132,0.461936,0.464661
Chad,0.424023,0.425148,0.427591,0.426260,0.426749,0.427589,0.428642,0.430031,NaN,NaN,NaN,NaN
Chile,0.492931,0.487240,0.480810,0.478965,0.476601,0.474623,0.470489,0.466809,0.464673,0.461788,0.459044,0.455785
China,0.417496,0.419426,0.422826,0.424862,0.427811,0.427153,0.426443,0.425994,0.418234,0.410654,0.410079,0.410305
Ecuador,0.488626,0.483989,0.478924,0.472173,0.463364,0.453907,0.445093,0.437680,0.431728,0.429536,0.425248,0.424350
Hungary,0.277325,0.275923,0.272970,0.271036,0.270137,0.271007,0.272935,0.274216,0.278617,0.281376,0.280284,0.277641
India,0.475990,0.477169,0.476792,0.478751,0.481493,0.484761,0.489253,0.494477,0.494913,0.494873,0.497074,0.497601
Kenya,0.470502,0.469579,0.470015,0.467160,0.466891,0.467044,0.467310,0.467252,0.466775,0.467404,0.468536,0.469112
Lesotho,0.509925,0.508952,0.508195,0.507159,0.505095,0.505016,0.503409,0.500661,0.498179,0.497029,0.495766,0.495672
Malawi,0.463758,0.460884,0.459149,0.458015,0.457522,0.458489,0.458446,0.457618,0.455361,0.455178,0.455747,0.456000
Mauritius,0.380992,0.381703,0.382170,0.382051,0.383758,0.385388,0.384773,0.384870,0.385625,0.385809,0.383857,0.384401
Mexico,0.471586,0.471145,0.464996,0.464797,0.464740,0.459854,0.455381,0.455284,0.451993,0.449993,0.445655,0.439478
Montenegro,NaN,0.381978,0.381777,0.383230,0.382965,0.385377,0.385495,0.386667,0.385725,0.385501,0.383168,0.381863
Morocco,0.416425,0.415757,0.414862,0.415598,0.415515,0.415779,0.415996,0.416337,0.416655,0.417055,0.416593,NaN
Namibia,0.673099,0.673610,0.673752,0.673941,0.671761,0.669987,0.669962,0.669075,0.667086,0.667520,0.666560,0.666034
Nigeria,0.437222,0.436439,0.436412,0.436615,0.436519,0.436415,0.436019,0.435366,0.434272,0.432563,0.430721,0.429833
Pakistan,0.343902,0.344955,0.345055,0.345175,0.344646,0.343180,0.343306,0.345336,0.344125,0.343865,0.343749,0.343351
Paraguay,0.505215,0.494780,0.492442,0.486264,0.479530,0.475879,0.479182,0.479956,0.469079,0.470427,0.469839,0.462783
Peru,0.524296,0.520375,0.514359,0.505296,0.494336,0.484870,0.475760,0.464997,0.460379,0.456002,0.449557,0.449204
Poland,0.316002,0.318754,0.316789,0.313574,0.311397,0.309840,0.310160,0.307854,0.308317,0.312626,0.304094,0.297596
Romania,0.310488,0.319811,0.329609,0.330487,0.328280,0.325687,0.325886,0.326269,0.328916,0.331805,0.336619,0.335716
Rwanda,0.512383,0.515393,0.513608,0.512745,0.512716,0.513109,0.512363,0.512786,0.511568,0.511280,0.510751,0.509614
Seychelles,0.427561,0.426687,0.426963,0.426211,0.425823,0.427415,0.428275,0.428840,0.428965,0.426658,NaN,NaN
S.A,0.627275,0.629702,0.632091,0.634358,0.636537,0.635301,0.635801,0.634215,0.632759,0.631425,0.629303,0.627564
Tunisia,0.408383,0.406607,0.404747,0.403498,0.402596,0.401282,0.399297,0.397251,0.394169,0.393057,0.392049,0.390968
Turkey,0.420109,0.417709,0.413696,0.411338,0.409656,0.406582,0.405161,0.403109,0.400751,0.398958,0.398531,0.399537
Uganda,0.452936,0.451785,0.451197,0.451089,0.449898,0.449802,0.449548,0.448601,0.447136,0.446677,0.446826,0.447604
Zambia,0.550650,0.551710,0.552987,0.555838,0.557042,0.557060,0.558546,0.557177,0.557102,0.558957,0.558794,0.559411

In [104]:
data.to_excel("gini_clean.xlsx")